services:
  - type: web
    name: my-flask-app
    env: python
    plan: free
    buildCommand:
    sudo apt-get update
    sudo apt-get install -y tesseract-ocr
    which tesseract
    pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: supersecretkey
      - key: DATABASE_URL
        value: postgresql://user:password@localhost:5432/mydatabase
      - key: DEBUG
        value: "False"
    autoDeploy: true
    region: oregon
